Add support for new async validation endpoints
kontent-ai/management-sdk-net pull request #190
Opened 2022-07-21 13:05 UTC by huluvu21

### Motivation

We want to cover the new async project validation endpoints in their raw form. The PR can be merger after the feature is released.

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

It would be great to test those endpoints after the release to production to make sure.

2022-08-01 10:11 UTC, gormal requested changes
Changes look great! There are missing tests for endpointUrlBuilder and a few nitpicks.

2022-08-01 10:11 UTC, gormal commented on Kontent.Ai.Management/IManagementClient.cs
> +    Task<AsyncValidationTask> InitiateProjectAsyncValidationTaskAsync();
ManagementClient should return *Model

2022-08-01 10:11 UTC, gormal commented on Kontent.Ai.Management/IManagementClient.cs
> +    Task<AsyncValidationTask> GetAsyncValidationTaskAsync(Guid taskId);
ManagementClient should return *Model

2022-08-01 10:11 UTC, gormal commented on Kontent.Ai.Management/IManagementClient.cs
> +    Task<IListingResponseModel<AsyncValidationTaskIssue>> ListAsyncValidationTaskIssuesAsync(Guid taskId);
ManagementClient should return *Model

2022-08-02 20:05 UTC, huluvu21 commented
> Changes look great! There are missing tests for endpointUrlBuilder and a few nitpicks.

All right. Done (fingers crossed).

2022-08-04 11:41 UTC, gormal approved these changes

2022-08-04 12:16 UTC, merged