201 - support for_default values in modular content and asset elements
kontent-ai/management-sdk-net pull request #202
Opened 2022-08-22 12:21 UTC by Iorethan

### Motivation

https://github.com/kontent-ai/management-sdk-net/issues/201

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

2022-08-22 12:47 UTC, robertstebel commented
The code is fine from the team perspective, but I am missing any release date here so I suppose @Iorethan will contact @gormal

2022-08-25 11:01 UTC, gormal requested changes
Great job! I have some questions tho. 

1. What about code samples, do they need to be updated? 
2. Has this been tested against a real project?

2022-08-25 12:31 UTC, Iorethan commented
> Great job! I have some questions tho.
> 
> 1. What about code samples, do they need to be updated?
> 2. Has this been tested against a real project?

1. I don't think thats needed. There is code sample only for string element, all other elements with default values are without code sample. There is nothing special about linked items and assets that would warrant a code sample.
2. No and so far it's not possible because the required changes to Kontent app are not finished yet.

2022-08-29 11:16 UTC, Iorethan commented on Kontent.Ai.Management.Tests/Data/ContentType/ContentType.json
> +      "default": {
Yes it can. The two settings don't interfere with each other.

2022-08-29 12:02 UTC, Iorethan commented on Kontent.Ai.Management/Models/Shared/AssetWithRenditionsReference.cs
> +    private AssetWithRenditionsReference(Guid id) : this(Reference.ById(id), null as IEnumerable<Reference>)
The `null` was not necessary but after rewriting this with `JsonConverter` the constructor was removed completely.

2022-08-29 12:15 UTC, Iorethan commented on Kontent.Ai.Management/Models/Types/Elements/AssetDefaultValueModel.cs
> +public class AssetDefaultValueModel : ElementDefaultValue<TypeValue<IEnumerable<AssetWithRenditionsReference>>, IEnumerable<AssetWithRenditionsReference>> { }
Done

2022-08-30 08:31 UTC, Simcsa commented
Regarding the release dates:
The asset default value will be released 31.8.
The linked item default value will be released 14.9.

2022-09-08 08:48 UTC, gormal reviewed
The changes look great. Once the testing is finished the PR can be merged.

2022-09-12 11:47 UTC, Tomas-Kristof commented
Testing (against production via console app & .NET SDK) - **OK**

- Asset element, Linked items element - models contains property for default value, default value can be read and set

2022-09-12 11:49 UTC, gormal approved these changes
LGTM!

2022-09-15 07:59 UTC, merged