Add support for displayTimeZone of DateTime element
kontent-ai/management-sdk-net pull request #204
Opened 2022-09-07 13:30 UTC by Radimersky

### Motivation

Which issue does this fix? Fixes #KCL-9004`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

A new property "displayTimeZone" was added to DateTime element which affects following MAPI endpoints:
- Publish or schedule a language variant
- Unpublish or schedule unpublishing of a language variant
- Upsert a language variant

The changes needs to be reflected in the MAPI v2 docs + code samples and SDK

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

All operations should be covered in tests.

2022-09-08 09:21 UTC, gormal requested changes
Hi, thanks for your contribution!

Unit tests should be extended to test the new property. Please have look at ElementBuilderTests.cs and ElementModelProviderTests.cs files.

Is the PR with code samples ready? Could you provide a link?

2022-09-19 13:13 UTC, Radimersky commented
> Hi, first of all, thanks for your contribution! I would like to see some unit tests for the property. Please have look at ElementBuilderTests.cs and ElementModelProviderTests.cs files.
> 
> Also, is the PR with code samples ready? Could you provide a link?

Hi, sorry for the delay, I was on vacation.
I have extended the tests as you have suggested. 
Here is a link to docs code samples https://github.com/Kontent-ai-Learn/kontent-ai-learn-code-samples/pull/60

2022-09-23 08:39 UTC, gormal submitted a review, later dismissed
LGTM!

2022-09-23 08:57 UTC, gormal approved these changes

2022-09-23 09:01 UTC, merged