new workflow tests
kontent-ai/management-sdk-net pull request #232
Opened 2023-02-23 14:51 UTC by gormal

### Motivation

new unit test for workflow

2023-03-03 16:20 UTC, Sevitas requested changes

2023-03-03 16:20 UTC, Sevitas commented on Kontent.Ai.Management.Tests/ManagementClientTests/WorkflowTests.cs
> +
extra line

2023-03-03 16:20 UTC, Sevitas commented on Kontent.Ai.Management.Tests/ManagementClientTests/WorkflowTests.cs
> +
extra line

2023-03-03 16:20 UTC, Sevitas commented on Kontent.Ai.Management.Tests/ManagementClientTests/WorkflowTests.cs
> +        static protected (Reference Identifier, string UrlSegment) ByCodename => (Reference.ByCodename("codename"), "codename/codename");
can be private

2023-03-03 16:20 UTC, Sevitas commented on Kontent.Ai.Management.Tests/ManagementClientTests/WorkflowTests.cs
> +        public IEnumerable<(LanguageVariantIdentifier Identifier, string Url)> GetPermutation()
can be private

2023-03-03 16:20 UTC, Sevitas commented on Kontent.Ai.Management.Tests/ManagementClientTests/WorkflowTests.cs
> +    private class CombinationOfIdentifiers : CombinationOfVariantIdentifiersAndUrl, IEnumerable<object[]>
not used

2023-03-03 16:20 UTC, Sevitas commented on Kontent.Ai.Management.Tests/ManagementClientTests/WorkflowTests.cs
> +            foreach (var (Identifier, Url) in GetPermutation())
should be lowercased

2023-03-09 11:37 UTC, gormal commented on Kontent.Ai.Management.Tests/ManagementClientTests/WorkflowTests.cs
> +        public IEnumerable<(LanguageVariantIdentifier Identifier, string Url)> GetPermutation()
I don't think this can be private.

2023-03-09 11:39 UTC, gormal commented on Kontent.Ai.Management.Tests/ManagementClientTests/WorkflowTests.cs
> +    private class CombinationOfIdentifiers : CombinationOfVariantIdentifiersAndUrl, IEnumerable<object[]>
fixed

2023-03-09 11:47 UTC, gormal commented on Kontent.Ai.Management.Tests/ManagementClientTests/WorkflowTests.cs
> +
fixed

2023-03-09 11:53 UTC, merged