Add asset codename
kontent-ai/management-sdk-net pull request #250
Opened 2023-08-17 07:41 UTC by VladimirO-kontent

### Motivation

Which issue does this fix? Fixes #249

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2023-08-17 09:06 UTC, Sevitas requested changes

2023-08-17 09:06 UTC, Sevitas commented on Kontent.Ai.Management.Tests/ManagementClientTests/AssetRenditionTests.cs
Shouldn't by asset codename also work for renditions as well?

2023-08-17 09:24 UTC, VladimirO-kontent commented on Kontent.Ai.Management.Tests/ManagementClientTests/AssetTests.cs
>      public async Task GetAssetAsync_StronglyTyped_ByCodename_Throws()
Fixed

2023-08-17 09:25 UTC, VladimirO-kontent commented on Kontent.Ai.Management.Tests/ManagementClientTests/AssetRenditionTests.cs
Yes, I have missed it in one test. The others should still throw since renditions themselves don't have codenames, only assets do.

2023-08-17 12:00 UTC, Sevitas approved these changes

2023-09-13 03:37 UTC, pokornyd approved these changes

2023-09-13 03:37 UTC, merged