Add new webhooks and rename legacy webhooks
kontent-ai/management-sdk-net pull request #254
Opened 2023-12-13 11:05 UTC by lenkaklimcikova

### Motivation

Which issue does this fix? Fixes #`issue number`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2023-12-19 10:21 UTC, Sevitas requested changes

2023-12-19 10:21 UTC, Sevitas commented on Kontent.Ai.Management/Models/Webhooks/Triggers/Asset/AssetActionModel.cs
> +/// Represents asset actions.
singular - > Represents asset action.

2023-12-19 10:21 UTC, Sevitas commented on Kontent.Ai.Management/Models/Webhooks/Triggers/ContentItem/ContentItemActionModel.cs
> +/// Represents content item actions.
singular - > Represents content item action.

2023-12-19 10:21 UTC, Sevitas commented on Kontent.Ai.Management/Models/Webhooks/Triggers/ContentType/ContentTypeActionModel.cs
> +/// Represents content type actions.
singular - > Represents * action.

2023-12-19 10:21 UTC, Sevitas commented on Kontent.Ai.Management/Models/Webhooks/Triggers/Language/LanguageActionModel.cs
> +/// Represents language actions.
singular - > Represents * action.

2023-12-19 10:21 UTC, Sevitas commented on Kontent.Ai.Management/Models/Webhooks/Triggers/Taxonomy/TaxonomyActionModel.cs
> +/// Represents taxonomy actions.
singular - > Represents * action.

2023-12-19 10:21 UTC, Sevitas commented on Kontent.Ai.Management/Models/Webhooks/Triggers/DeliverySlotModel.cs
> +public enum DeliverySlotModel
DeliverySlot

2023-12-19 10:21 UTC, Sevitas commented on Kontent.Ai.Management/Models/Webhooks/Triggers/DeliverySlotModel.cs
> +/// Represents the delivery slot model.
/// Represents the delivery slot.

2023-12-19 10:21 UTC, Sevitas commented on Kontent.Ai.Management/Models/LegacyWebhooks/LegacyWebhookCreateModel.cs
> +/// Represents the webhook create model.
/// Represents the legacy webhook create model.

2023-12-20 15:59 UTC, lenkaklimcikova commented on Kontent.Ai.Management.Tests/ManagementClientTests/LegacyWebhookTests.cs
> +public class LegacyWebhookTests : IClassFixture<FileSystemFixture>
fixed

2023-12-20 16:03 UTC, lenkaklimcikova commented on Kontent.Ai.Management/Models/LegacyWebhooks/Triggers/LegacyWebhookTriggersModel.cs
good point thanks, didn't think about changing the old ones,too :D fixed

2023-12-21 12:15 UTC, lenkaklimcikova commented on Kontent.Ai.Management/Models/Webhooks/Triggers/WebhookEventsFilterModel.cs
> +public enum WebhookEventsFilterModel
fixed

2023-12-21 12:45 UTC, lenkaklimcikova commented on Kontent.Ai.Management/Models/Webhooks/WebhookModel.cs
>      /// Gets or sets the specific events that trigger the webhook. At least one valid trigger is required.
I did it with an example in the legacy webhooks, it was not there either. Should I add it into the LegacyWebhookModel as well then? :)

2023-12-21 13:07 UTC, lenkaklimcikova commented on Kontent.Ai.Management.Tests/ManagementClientTests/LegacyWebhookTests.cs
> +    public async void GetWebhookAsync_ByCodename_GetsWebhook()
Yeah, those were wrongly written before, I fixed it in new tests but forgot to fix the old ones.

2024-01-02 12:59 UTC, Sevitas commented
You have renamed the action enums to names with suffix Enum, please keep it consistent in the namespace _Kontent.Ai.Management.Models.Webhooks_. There are enums without this suffix. I'd prefer removing those suffixes

2024-01-02 13:30 UTC, Sevitas commented on Kontent.Ai.Management/Models/Webhooks/WebhookModel.cs
>      /// Gets or sets the specific events that trigger the webhook. At least one valid trigger is required.
Please add it for LegacyWebhookModel as well.

2024-01-03 18:39 UTC, lenkaklimcikova commented on Kontent.Ai.Management/Models/Webhooks/WebhookModel.cs
>      /// Gets or sets the specific events that trigger the webhook. At least one valid trigger is required.
added

2024-01-04 11:23 UTC, Sevitas approved these changes

2024-01-12 15:38 UTC, pokornyd commented on Kontent.Ai.Management/Models/Webhooks/Triggers/Language/LanguageActionModel.cs
> +/// Represents language actions.
fixed typo

2024-01-15 08:19 UTC, pokornyd submitted a review, later dismissed
following internal discussion, the target framework was updated to .NET 8.0 for all projects under the solution.

2024-01-15 08:29 UTC, pokornyd approved these changes

2024-01-15 09:04 UTC, merged