EN-125 Add due date to content item variant
kontent-ai/management-sdk-net pull request #262
Opened 2024-03-27 06:52 UTC by arguit

### Motivation

Which issue does this fix? Fixes #`issue number`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2024-03-27 10:24 UTC, VladimirO-kontent requested changes
You should also update PutLanguageVariant in CmApiV2.cs.

2024-03-27 10:24 UTC, VladimirO-kontent commented on Kontent.Ai.Management/Models/LanguageVariants/DueDateResponseModel.cs
> +public class DueDateResponseModel
This class is also used in requests, it should not have response in name.

2024-04-02 08:21 UTC, VladimirO-kontent approved these changes

2024-04-08 10:25 UTC, pokornyd approved these changes

2024-04-08 10:25 UTC, merged