EN-261 Add schedule publish and unpublish endpoint to Management API SDK
kontent-ai/management-sdk-net pull request #275
Opened 2024-09-11 11:26 UTC by mrnustik

### Motivation

Which issue does this fix? Fixes #`issue number`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [x] Code follows coding conventions held in this repo
- [x] Automated tests have been added
- [x] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2025-02-05 14:11 UTC, pokornyd requested changes

2025-02-05 14:11 UTC, pokornyd commented on Kontent.Ai.Management/Models/Publishing/SchedulePublishAndUnpublishModel.cs
> +    /// </summary>
according to [api specs](https://kontent.ai/learn/docs/apis/openapi/management-api-v2/#operation/schedule-publishing-and-unpublishing-of-a-language-variant), there's only one `display_timezone` property, not two separate for publishing and unpublishing

2025-02-05 14:11 UTC, pokornyd commented on Kontent.Ai.Management/IManagementClient.cs
> +    Task SchedulePublishAndUnpublishOfLanguageVariantAsync(LanguageVariantIdentifier identifier, SchedulePublishAndUnpublishModel schedule);
nitpick, but for the sake of consistency, I would rename this to `SchedulePublishingAndUnpublishingOfLanguageVariantAsync`. the six extra symbols don't make that much of a difference and it would match the endpoint name in API docs :)

2025-02-05 14:11 UTC, pokornyd commented on Kontent.Ai.Management/ManagementClient.Publishing.cs
> +    public async Task SchedulePublishAndUnpublishOfLanguageVariantAsync(LanguageVariantIdentifier identifier, SchedulePublishAndUnpublishModel schedule)
ditto rename

2025-02-10 13:30 UTC, mrnustik commented on Kontent.Ai.Management/Models/Publishing/SchedulePublishAndUnpublishModel.cs
> +    /// </summary>
Hi, the [api specs](https://kontent.ai/learn/docs/apis/openapi/management-api-v2/#tag/Publishing) should now be up to date.

2025-02-10 13:32 UTC, mrnustik commented on Kontent.Ai.Management/IManagementClient.cs
> +    Task SchedulePublishAndUnpublishOfLanguageVariantAsync(LanguageVariantIdentifier identifier, SchedulePublishAndUnpublishModel schedule);
Should be resolved. :)

2025-02-10 13:32 UTC, mrnustik commented on Kontent.Ai.Management/ManagementClient.Publishing.cs
> +    public async Task SchedulePublishAndUnpublishOfLanguageVariantAsync(LanguageVariantIdentifier identifier, SchedulePublishAndUnpublishModel schedule)
Should be resolved. :)

2025-02-11 09:01 UTC, pokornyd approved these changes

2025-02-11 09:01 UTC, merged